spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
    url: jdbc:mysql://db:3306/ShopForHome?useSSL=false&serverTimezone=UTC
    platform: mysql
    initialization-mode: always
    continue-on-error: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?

server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400
